name: Odyssey-Combat
version: '1.1'
main: me.lyamray.odysseyCombat.OdysseyCombat
api-version: '1.21'
load: STARTUP
authors: [ LyamRay ]
softdepend: [Citizens]
description: Combat plugin made by LyamRay for Odyssey Kingdom!
